In [ ]:
# # The Groupby() function

# Definition of GroupBy
# In Pandas, the groupby() function is used to split the data into groups based on some criteria. It allows you to group rows that have the same values in a particular column and then perform some mathematical operation (like sum, average, or count) on another column.

# The Main Concept: "Split-Apply-Combine"
# Yeh groupby ka sab se barha concept hai. Iske 3 main steps hotay hain:

# Split:
# Breaking the dataset into smaller groups based on a specific column.
# (Data ko tukron mein baantna kisi ek column ki wajah se).

# Apply:
# Computing a mathematical function (like sum(), mean(), count()) on each group independently.
# (Har tukray par alag se calculation karna).

# Combine:
# Merging the results back into a single data structure (like a new DataFrame or Series).
# (Saray results ko wapis jod kar ek table bana dena).

# Syntax Breakdown
# Python
# df.groupby('Column_to_Group_By')['Target_Column'].function()
# df: Aapka dataset (DataFrame).

# groupby('Column_to_Group_By'): Woh column jis mein categories hain (e.g., City, Gender, Sector).

# ['Target_Column']: Woh column jis par aapko calculation karni hai (e.g., Sales, Profit, Age).

# .function(): Woh calculation jo aap karna chahte hain (e.g., .sum(), .mean(), .max()).

In [5]:
import pandas as pd

data = pd.read_csv("Fortune_500.csv",encoding="latin-1")

In [6]:
data

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
1,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"
2,3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718"
3,4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056"
4,5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439"
...,...,...,...,...,...,...,...,...,...,...
495,496,Michaels Cos.,"31,000",517.0,"$5,197",5.8%,$378.2,4.2%,"$2,148","$4,229"
496,497,Toll Brothers,"4,200",576.0,"$5,170",23.9%,$382.1,5.2%,"$9,737","$5,872"
497,498,Yahoo,"8,500",513.0,"$5,169",4.0%,-$214.3,-,"$48,083","$44,391"
498,499,Vistra Energy,"4,431",NaN,"$5,164",-,-,-,"$15,167","$6,968"
499,500,ABM Industries,"1,10,000",485.0,"$5,145",-2.8%,$57.2,-25.0%,"$2,281","$2,428"

In [7]:
data.head(2)

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
1,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"

In [17]:
prof = data.groupby("Company Name")

In [18]:
prof

In [19]:
len(data)

500

In [20]:
len(prof)

497

In [22]:
prof.size().sort_values(ascending=False)

Company Name
Avnet                  2
Alcoa                  2
Regions Financial      2
Whirlpool              1
W.R. Berkley           1
                      ..
Activision Blizzard    1
Adobe Systems          1
Advance Auto Parts     1
Aetna                  1
Weyerhaeuser           1
Length: 497, dtype: int64

In [23]:
prof.first()

,Rank,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
Company Name,,,,,,,,,
3M,94,"91,584",93.0,"$30,109",-0.5%,"$5,050.0",4.5%,"$32,906","$1,14,338"
A-Mark Precious Metals,395,"83,000",426.0,"$6,784",11.8%,$9.3,31.5%,$437,$120
ABM Industries,500,"1,10,000",485.0,"$5,145",-2.8%,$57.2,-25.0%,"$2,281","$2,428"
ADP,240,"57,000",248.0,"$11,668",1.7%,"$1,492.5",2.8%,"$43,670","$45,963"
AECOM,161,"87,000",156.0,"$17,411",-3.2%,$96.1,-,"$13,727","$5,528"
...,...,...,...,...,...,...,...,...,...
Yum China Holdings,399,"4,20,000",NaN,"$6,752",-,$502.0,-,"$3,727","$10,453"
Zimmer Biomet Holdings,352,"18,500",431.0,"$7,684",28.1%,$305.9,108.1%,"$26,684","$24,571"
eBay,310,"12,600",300.0,"$8,979",-5.4%,"$7,266.0",321.2%,"$23,847","$36,232"
iHeartMedia,426,"18,700",414.0,"$6,274",0.5%,-$296.3,-,"$12,862",$330
salesforce.com,326,"25,000",386.0,"$8,392",25.9%,$179.6,-,"$17,585","$58,362"

In [25]:
prof.last()

,Rank,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
Company Name,,,,,,,,,
3M,94,"91,584",93.0,"$30,109",-0.5%,"$5,050.0",4.5%,"$32,906","$1,14,338"
A-Mark Precious Metals,395,"83,000",426.0,"$6,784",11.8%,$9.3,31.5%,$437,$120
ABM Industries,500,"1,10,000",485.0,"$5,145",-2.8%,$57.2,-25.0%,"$2,281","$2,428"
ADP,240,"57,000",248.0,"$11,668",1.7%,"$1,492.5",2.8%,"$43,670","$45,963"
AECOM,161,"87,000",156.0,"$17,411",-3.2%,$96.1,-,"$13,727","$5,528"
...,...,...,...,...,...,...,...,...,...
Yum China Holdings,399,"4,20,000",NaN,"$6,752",-,$502.0,-,"$3,727","$10,453"
Zimmer Biomet Holdings,352,"18,500",431.0,"$7,684",28.1%,$305.9,108.1%,"$26,684","$24,571"
eBay,310,"12,600",300.0,"$8,979",-5.4%,"$7,266.0",321.2%,"$23,847","$36,232"
iHeartMedia,426,"18,700",414.0,"$6,274",0.5%,-$296.3,-,"$12,862",$330
salesforce.com,326,"25,000",386.0,"$8,392",25.9%,$179.6,-,"$17,585","$58,362"

In [28]:
prof.groups

{'3M': [93], 'A-Mark Precious Metals': [394], 'ABM Industries': [499], 'ADP': [239], 'AECOM': [160], 'AES': [193], 'AGCO': [369], 'AIG': [54], 'AK Steel Holding': [440], 'AT&T': [8], 'AbbVie': [110], 'Abbott Laboratories': [134], 'Activision Blizzard': [405], 'Adobe Systems': [442], 'Advance Auto Parts': [291], 'Aetna': [42], 'Aflac': [125], 'Air Products & Chemicals': [293], 'Airgas': [488], 'Alaska Air Group': [437], 'Albertsons Cos.': [48], 'Alcoa': [227, 299], 'Alleghany': [427], 'Alliance Data Systems': [377], 'Allstate': [83], 'Ally Financial': [285], 'Alphabet': [26], 'Altria Group': [147], 'AmTrust Financial Services': [474], 'Amazon.com': [11], 'Ameren': [430], 'American Airlines Group': [66], 'American Electric Power': [166], 'American Express': [85], 'American Family Insurance Group': [314], 'American Financial Group': [410], 'American Tower': [448], 'Ameriprise Financial': [238], 'AmerisourceBergen': [10], 'Amgen': [122], 'Amphenol': [423], 'Anadarko Petroleum': [343], 'Anixter International': [358], 'Anthem': [28], 'Apache': [487], 'Apple': [2], 'Applied Materials': [264], 'Aramark': [191], 'Archer Daniels Midland': [44], 'Arrow Electronics': [117], 'Arthur J. Gallagher': [461], 'Asbury Automotive Group': [409], 'Ascena Retail Group': [383], 'Assurant': [360], 'Auto-Owners Insurance': [397], 'AutoNation': [128], 'AutoZone': [269], 'Autoliv': [282], 'Avery Dennison': [429], 'Avis Budget Group': [318], 'Avnet': [107, 108], 'Avon Products': [443], 'BB&T Corp.': [244], 'Baker Hughes': [284], 'Ball': [305], 'Bank of America Corp.': [25], 'Bank of New York Mellon Corp.': [176], 'Baxter International': [280], 'Becton Dickinson': [224], 'Bed Bath & Beyond': [232], 'Berkshire Hathaway': [1], 'Berry Global Group': [412], 'Best Buy': [71], 'Big Lots': [494], 'Biogen': [247], 'BlackRock': [254], 'Boeing': [23], 'Booz Allen Hamilton Holding': [480], 'BorgWarner': [304], 'Boston Scientific': [326], 'Bristol-Myers Squibb': [146], 'Builders FirstSource': [420], 'Burlington Stores': [462], 'C.H. Robinson Worldwide': [211], 'CBRE Group': [213], 'CBS': [192], 'CDW': [198], 'CH2M Hill': [493], 'CHS': [92], 'CMS Energy': [418], 'CST Brands': [306], 'CSX': [256], 'CVS Health': [6], 'CalAtlantic Group': [414], 'Calpine': [399], 'Campbell Soup': [338], 'Capital One Financial': [99], 'CarMax': [173], 'Cardinal Health': [14], 'CaseyÕs General Stores': [422], ...}

In [29]:
prof.get_group("Walmart")

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"

In [30]:
prof.get_group("Walmart").size

10

In [31]:
prof.sum()

,Rank,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
Company Name,,,,,,,,,
3M,94,"91,584",93.0,"$30,109",-0.5%,"$5,050.0",4.5%,"$32,906","$1,14,338"
A-Mark Precious Metals,395,"83,000",426.0,"$6,784",11.8%,$9.3,31.5%,$437,$120
ABM Industries,500,"1,10,000",485.0,"$5,145",-2.8%,$57.2,-25.0%,"$2,281","$2,428"
ADP,240,"57,000",248.0,"$11,668",1.7%,"$1,492.5",2.8%,"$43,670","$45,963"
AECOM,161,"87,000",156.0,"$17,411",-3.2%,$96.1,-,"$13,727","$5,528"
...,...,...,...,...,...,...,...,...,...
Yum China Holdings,399,"4,20,000",0.0,"$6,752",-,$502.0,-,"$3,727","$10,453"
Zimmer Biomet Holdings,352,"18,500",431.0,"$7,684",28.1%,$305.9,108.1%,"$26,684","$24,571"
eBay,310,"12,600",300.0,"$8,979",-5.4%,"$7,266.0",321.2%,"$23,847","$36,232"
iHeartMedia,426,"18,700",414.0,"$6,274",0.5%,-$296.3,-,"$12,862",$330
salesforce.com,326,"25,000",386.0,"$8,392",25.9%,$179.6,-,"$17,585","$58,362"

In [44]:
import pandas as pd

# Data load karein
data = pd.read_csv("Fortune_500.csv", encoding='latin1')

def clean_currency(value):
    if isinstance(value, str):
        # 1. $, commas aur faltu spaces khatam karein
        clean_val = value.replace('$', '').replace(',', '').strip()
        
        # 2. Agar value bracket mein hai (jaise loss), to minus sign lagayein
        if clean_val.startswith('(') and clean_val.endswith(')'):
            clean_val = '-' + clean_val[1:-1]
        
        # 3. Agar value sirf '-' hai ya khali hai, to usay 0.0 kardein
        if clean_val == '-' or clean_val == '':
            return 0.0
            
        try:
            return float(clean_val)
        except ValueError:
            # Agar koi aur ajeeb cheez hai jo number nahi ban sakti
            return 0.0
    return value

# Cleaning apply karein
data['Revenues'] = data['Revenues'].apply(clean_currency)
data['Profits'] = data['Profits'].apply(clean_currency)

print("Data Clean ho gaya hai! Ab 'Revenues' aur 'Profits' numbers ban chuke hain.")

Data Clean ho gaya hai! Ab 'Revenues' aur 'Profits' numbers ban chuke hain.