In [1]:
# The dropna() method

In [2]:
import pandas as pd

In [3]:
import pandas as pd
import numpy as np

# 1. Aik base pattern banate hain (8 rows ka)
# Isme jaan boojh kar 'None' dala gaya hai jo Pandas mein NaN ban jayega
raw_data = {
    'PassengerId': [1, 2, 3, 4, 5, 6, 7, 8],
    'Survived': [0, 1, 1, 0, 0, None, 1, 0],
    'Pclass': [3, 1, 3, 1, 3, 3, 1, 2],
    'Name': ['Braund', 'Cumings', 'Heikkinen', 'Futrelle', 'Allen', None, 'McCarthy', 'Palsson'],
    'Sex': ['male', 'female', 'female', 'female', 'male', 'male', None, 'male'],
    'Age': [22.0, 38.0, 26.0, 35.0, None, 54.0, 2.0, 27.0],
    'SibSp': [1, 1, 0, 1, 0, 0, 3, None],
    'Parch': [0, 0, 0, 0, 0, 0, 1, 1],
    'Ticket': ['A/5 21171', 'PC 17599', 'STON/O2', '113803', '373450', None, '17463', '349909'],
    'Fare': [7.25, 71.28, 7.92, 53.10, 8.05, 8.45, None, 21.07],
    'Cabin': [None, 'C85', None, 'C123', None, None, 'E46', None],
    'Embarked': ['S', 'C', 'S', 'S', 'S', 'Q', 'S', None]
}

data_repeated = {col: np.tile(val, 100) for col, val in raw_data.items()}

# 3. DataFrame create karein
df = pd.DataFrame(data_repeated)

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Braund,male,22.0,1,0,A/5 21171,7.25,NaN,S
1,2,1,1,Cumings,female,38.0,1,0,PC 17599,71.28,C85,C
2,3,1,3,Heikkinen,female,26.0,0,0,STON/O2,7.92,NaN,S
3,4,0,1,Futrelle,female,35.0,1,0,113803,53.1,C123,S
4,5,0,3,Allen,male,None,0,0,373450,8.05,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
795,4,0,1,Futrelle,female,35.0,1,0,113803,53.1,C123,S
796,5,0,3,Allen,male,None,0,0,373450,8.05,NaN,S
797,6,None,3,NaN,male,54.0,0,0,NaN,8.45,NaN,Q
798,7,1,1,McCarthy,NaN,2.0,3,1,17463,None,E46,S
799,8,0,2,Palsson,male,27.0,None,1,349909,21.07,NaN,NaN

In [2]:
import pandas as pd
import numpy as np

# Aapka base data
raw_data = {
    'PassengerId': [1, 2, 3, 4, 5, 6, 7, 8],
    'Survived': [0, 1, 1, 0, 0, None, 1, 0],
    'Pclass': [3, 1, 3, 1, 3, 3, 1, 2],
    'Name': ['Braund', 'Cumings', 'Heikkinen', 'Futrelle', 'Allen', None, 'McCarthy', 'Palsson'],
    'Sex': ['male', 'female', 'female', 'female', 'male', 'male', None, 'male'],
    'Age': [22.0, 38.0, 26.0, 35.0, None, 54.0, 2.0, 27.0],
    'SibSp': [1, 1, 0, 1, 0, 0, 3, None],
    'Parch': [0, 0, 0, 0, 0, 0, 1, 1],
    'Ticket': ['A/5 21171', 'PC 17599', 'STON/O2', '113803', '373450', None, '17463', '349909'],
    'Fare': [7.25, 71.28, 7.92, 53.10, 8.05, 8.45, None, 21.07],
    'Cabin': [None, 'C85', None, 'C123', None, None, 'E46', None],
    'Embarked': ['S', 'C', 'S', 'S', 'S', 'Q', 'S', None]
}

data_repeated = {col: np.tile(val, 100) for col, val in raw_data.items()}
df = pd.DataFrame(data_repeated)

# --- Naya Data Add Karte Hain ---
# 1. Poora Khali Column
df['Remarks'] = np.nan 

# 2. Aik Poori Khali Row (Row number 800 par add karte hain)
df.loc[800] = [np.nan] * len(df.columns)

print(f"Data Shape: {df.shape}")

Data Shape: (801, 13)

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Remarks
0,1.0,0,3.0,Braund,male,22.0,1,0.0,A/5 21171,7.25,NaN,S,NaN
1,2.0,1,1.0,Cumings,female,38.0,1,0.0,PC 17599,71.28,C85,C,NaN
2,3.0,1,3.0,Heikkinen,female,26.0,0,0.0,STON/O2,7.92,NaN,S,NaN
3,4.0,0,1.0,Futrelle,female,35.0,1,0.0,113803,53.1,C123,S,NaN
4,5.0,0,3.0,Allen,male,None,0,0.0,373450,8.05,NaN,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,5.0,0,3.0,Allen,male,None,0,0.0,373450,8.05,NaN,S,NaN
797,6.0,None,3.0,NaN,male,54.0,0,0.0,NaN,8.45,NaN,Q,NaN
798,7.0,1,1.0,McCarthy,NaN,2.0,3,1.0,17463,None,E46,S,NaN
799,8.0,0,2.0,Palsson,male,27.0,None,1.0,349909,21.07,NaN,NaN,NaN
800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_clean = df.dropna()
df_clean

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, Remarks]
Index: []

In [7]:
# 'how=all' ka matlab hai: "tabhi delete karo jab poori row khali ho"
df_clean = df.dropna(how='all')
df_clean

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Remarks
0,1.0,0,3.0,Braund,male,22.0,1,0.0,A/5 21171,7.25,NaN,S,NaN
1,2.0,1,1.0,Cumings,female,38.0,1,0.0,PC 17599,71.28,C85,C,NaN
2,3.0,1,3.0,Heikkinen,female,26.0,0,0.0,STON/O2,7.92,NaN,S,NaN
3,4.0,0,1.0,Futrelle,female,35.0,1,0.0,113803,53.1,C123,S,NaN
4,5.0,0,3.0,Allen,male,None,0,0.0,373450,8.05,NaN,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,4.0,0,1.0,Futrelle,female,35.0,1,0.0,113803,53.1,C123,S,NaN
796,5.0,0,3.0,Allen,male,None,0,0.0,373450,8.05,NaN,S,NaN
797,6.0,None,3.0,NaN,male,54.0,0,0.0,NaN,8.45,NaN,Q,NaN
798,7.0,1,1.0,McCarthy,NaN,2.0,3,1.0,17463,None,E46,S,NaN
799,8.0,0,2.0,Palsson,male,27.0,None,1.0,349909,21.07,NaN,NaN,NaN

In [8]:
df_clean.shape

(800, 13)

In [9]:
# axis=1 matlab Column. how='all' matlab jo poora khali ho.
df_no_empty_cols = df.dropna(axis=1, how='all')
df_no_empty_cols

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1.0,0,3.0,Braund,male,22.0,1,0.0,A/5 21171,7.25,NaN,S
1,2.0,1,1.0,Cumings,female,38.0,1,0.0,PC 17599,71.28,C85,C
2,3.0,1,3.0,Heikkinen,female,26.0,0,0.0,STON/O2,7.92,NaN,S
3,4.0,0,1.0,Futrelle,female,35.0,1,0.0,113803,53.1,C123,S
4,5.0,0,3.0,Allen,male,None,0,0.0,373450,8.05,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
796,5.0,0,3.0,Allen,male,None,0,0.0,373450,8.05,NaN,S
797,6.0,None,3.0,NaN,male,54.0,0,0.0,NaN,8.45,NaN,Q
798,7.0,1,1.0,McCarthy,NaN,2.0,3,1.0,17463,None,E46,S
799,8.0,0,2.0,Palsson,male,27.0,None,1.0,349909,21.07,NaN,NaN
800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_no_empty_cols.shape

(801, 12)

In [12]:
# Isse sirf wo rows jayengi jahan Name ya Age nahi likhi
df_final = df.dropna(subset=['Name', 'Age'])
df_final

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Remarks
0,1.0,0,3.0,Braund,male,22.0,1,0.0,A/5 21171,7.25,NaN,S,NaN
1,2.0,1,1.0,Cumings,female,38.0,1,0.0,PC 17599,71.28,C85,C,NaN
2,3.0,1,3.0,Heikkinen,female,26.0,0,0.0,STON/O2,7.92,NaN,S,NaN
3,4.0,0,1.0,Futrelle,female,35.0,1,0.0,113803,53.1,C123,S,NaN
6,7.0,1,1.0,McCarthy,NaN,2.0,3,1.0,17463,None,E46,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,2.0,1,1.0,Cumings,female,38.0,1,0.0,PC 17599,71.28,C85,C,NaN
794,3.0,1,3.0,Heikkinen,female,26.0,0,0.0,STON/O2,7.92,NaN,S,NaN
795,4.0,0,1.0,Futrelle,female,35.0,1,0.0,113803,53.1,C123,S,NaN
798,7.0,1,1.0,McCarthy,NaN,2.0,3,1.0,17463,None,E46,S,NaN
799,8.0,0,2.0,Palsson,male,27.0,None,1.0,349909,21.07,NaN,NaN,NaN

In [13]:
df_filled = df.fillna("Missing")

In [14]:
df_filled

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Remarks
0,1.0,0,3.0,Braund,male,22.0,1,0.0,A/5 21171,7.25,Missing,S,Missing
1,2.0,1,1.0,Cumings,female,38.0,1,0.0,PC 17599,71.28,C85,C,Missing
2,3.0,1,3.0,Heikkinen,female,26.0,0,0.0,STON/O2,7.92,Missing,S,Missing
3,4.0,0,1.0,Futrelle,female,35.0,1,0.0,113803,53.1,C123,S,Missing
4,5.0,0,3.0,Allen,male,Missing,0,0.0,373450,8.05,Missing,S,Missing
...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,5.0,0,3.0,Allen,male,Missing,0,0.0,373450,8.05,Missing,S,Missing
797,6.0,Missing,3.0,Missing,male,54.0,0,0.0,Missing,8.45,Missing,Q,Missing
798,7.0,1,1.0,McCarthy,Missing,2.0,3,1.0,17463,Missing,E46,S,Missing
799,8.0,0,2.0,Palsson,male,27.0,Missing,1.0,349909,21.07,Missing,Missing,Missing
800,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing

In [15]:
df_cleaned = df.fillna(
    {
        "Age":0,
        "Sex":'Unknown',
        "Cabin":"No Cabin"
    }
)

In [17]:
df_cleaned

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Remarks
0,1.0,0,3.0,Braund,male,22.0,1,0.0,A/5 21171,7.25,No Cabin,S,NaN
1,2.0,1,1.0,Cumings,female,38.0,1,0.0,PC 17599,71.28,C85,C,NaN
2,3.0,1,3.0,Heikkinen,female,26.0,0,0.0,STON/O2,7.92,No Cabin,S,NaN
3,4.0,0,1.0,Futrelle,female,35.0,1,0.0,113803,53.1,C123,S,NaN
4,5.0,0,3.0,Allen,male,0,0,0.0,373450,8.05,No Cabin,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,5.0,0,3.0,Allen,male,0,0,0.0,373450,8.05,No Cabin,S,NaN
797,6.0,None,3.0,NaN,male,54.0,0,0.0,NaN,8.45,No Cabin,Q,NaN
798,7.0,1,1.0,McCarthy,Unknown,2.0,3,1.0,17463,None,E46,S,NaN
799,8.0,0,2.0,Palsson,male,27.0,None,1.0,349909,21.07,No Cabin,NaN,NaN
800,NaN,NaN,NaN,NaN,Unknown,0,NaN,NaN,NaN,NaN,No Cabin,NaN,NaN

In [18]:
# Age ki khali jagah par sab logon ki average age bhar do
average_age = df['Age'].mean()
df['Age'] = df['Age'].fillna(average_age)

In [21]:
print(average_age)

29.142857142857142

In [22]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Remarks
0,1.0,0,3.0,Braund,male,22.0,1,0.0,A/5 21171,7.25,NaN,S,NaN
1,2.0,1,1.0,Cumings,female,38.0,1,0.0,PC 17599,71.28,C85,C,NaN
2,3.0,1,3.0,Heikkinen,female,26.0,0,0.0,STON/O2,7.92,NaN,S,NaN
3,4.0,0,1.0,Futrelle,female,35.0,1,0.0,113803,53.1,C123,S,NaN
4,5.0,0,3.0,Allen,male,29.142857,0,0.0,373450,8.05,NaN,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,5.0,0,3.0,Allen,male,29.142857,0,0.0,373450,8.05,NaN,S,NaN
797,6.0,None,3.0,NaN,male,54.0,0,0.0,NaN,8.45,NaN,Q,NaN
798,7.0,1,1.0,McCarthy,NaN,2.0,3,1.0,17463,None,E46,S,NaN
799,8.0,0,2.0,Palsson,male,27.0,None,1.0,349909,21.07,NaN,NaN,NaN
800,NaN,NaN,NaN,NaN,NaN,29.142857,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# Forward fill: Upar wali value niche copy hogi
df_filled = df.ffill()

# Check karne ke liye niche ye likhein
df_filled.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Remarks
0,1.0,0,3.0,Braund,male,22.0,1,0.0,A/5 21171,7.25,NaN,S,NaN
1,2.0,1,1.0,Cumings,female,38.0,1,0.0,PC 17599,71.28,C85,C,NaN
2,3.0,1,3.0,Heikkinen,female,26.0,0,0.0,STON/O2,7.92,C85,S,NaN
3,4.0,0,1.0,Futrelle,female,35.0,1,0.0,113803,53.1,C123,S,NaN
4,5.0,0,3.0,Allen,male,29.142857,0,0.0,373450,8.05,C123,S,NaN

In [26]:
# Ye original df ko hi update kar dega
df = df.ffill()

In [27]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Remarks
0,1.0,0,3.0,Braund,male,22.0,1,0.0,A/5 21171,7.25,NaN,S,NaN
1,2.0,1,1.0,Cumings,female,38.0,1,0.0,PC 17599,71.28,C85,C,NaN
2,3.0,1,3.0,Heikkinen,female,26.0,0,0.0,STON/O2,7.92,C85,S,NaN
3,4.0,0,1.0,Futrelle,female,35.0,1,0.0,113803,53.1,C123,S,NaN
4,5.0,0,3.0,Allen,male,29.142857,0,0.0,373450,8.05,C123,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,5.0,0,3.0,Allen,male,29.142857,0,0.0,373450,8.05,C123,S,NaN
797,6.0,0,3.0,Allen,male,54.0,0,0.0,373450,8.45,C123,Q,NaN
798,7.0,1,1.0,McCarthy,male,2.0,3,1.0,17463,8.45,E46,S,NaN
799,8.0,0,2.0,Palsson,male,27.0,3,1.0,349909,21.07,E46,S,NaN
800,8.0,0,2.0,Palsson,male,29.142857,3,1.0,349909,21.07,E46,S,NaN